spring.application.name=NarmadaCart
spring.datasource.url=jdbc:postgresql://localhost:5432/narmada_cart
spring.datasource.username=postgres
spring.datasource.password=OmNamahShivayOm
spring.jpa.hibernate.ddl-auto=update